### ISSUE TITLE
Your prefrences cannot be read on garlicwallet linux

### ISSUE THREAD

**Issue by Detailer** [garlicoin-project/copay-grlc#4]
When launching the wallet a dialogue box says preferences can be loaded, options like request spending password are not saved.

**Comment by Detailer** [comment]
![Example](https://user-images.githubusercontent.com/10812864/36494382-e70f932c-1757-11e8-8e88-dcbae11f3cd0.png)

**Comment by ryan-shaw** [comment]
Thanks- will take a look into it

**Comment by Detailer** [comment]
This does not happen while launching with sudo but the preferences are still not saved

**Comment by Detailer** [comment]
I was able to solve the preferences cannot be read dialogue box by changing the permission of the .config folder for GarlicWallet from root to my user. I think I ran GarlicWallet with sudo somewhere that caused this problem. But the "require spending password" checkbox  still gets unticked every time.
